name: Release

on:
  workflow_dispatch:
    inputs: {}
  release:
    types: [released]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build for release
    uses: wdonray/manage-my-debt-v2/.github/workflows/build.yml@main
    secrets:
      PACKAGES_AUTH_TOKEN: ${{ secrets.PACKAGES_AUTH_TOKEN }}
